### ISSUE TITLE
Finish Adding Serverdex Emojis 

### ISSUE THREAD

**Issue by Xieon** [Xieons-Gaming-Corner/public_records#12]
# Task List for Project Phoenix - Aizen Integration and Repository Updates

### Categories:
- **Added to Project Phoenix on DDP**
- **Added to Aizen on DDP**
- **Added to Public Repo for Images**
- **Emoji Code for Aizen Added to Emoji Code Library**
- **Emoji Code for PP Added to Emoji Code Library**

---

- **Ho-Oh**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Umbreon**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Charizard**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Haxorus**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Entei**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Mawile**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Golissipod**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Iron Thorns**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Iron Hands**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Roaring Moon**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Zacian-Crowned**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Absol**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Armarouge/Charcadet/Ceruledge**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Azumarill**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **King Gambit**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Ninetails**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Eevee**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Flareon**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Vaporeon**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Jolteon**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Garbador: Reznovs Ghost Haunts You**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Emboar**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Greninja**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Iron Moth**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Zangoose**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Iron Valiant [Rental for Bot Owners]**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Jirachi (Thankful'23 Gift)**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Kirlia/Tinkaton**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Lapras/Aron/Rhyhorn**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Jigglypuff, Ralts (GA Prizes)**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **SOLD: Jigglypuff, Kirlia, Ninetails, Ralts**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Zoroark**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Larvitar/Pupitar/Tyranitar**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Litten**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Lechonk**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Lycanroc**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Magikarp**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Marowak's Ghost**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Metagross**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Meowth (Crypto)**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Mimikyu**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Mudkip**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Naganadel**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **SuperDonor-LegendaryRole**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Overqwil**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added to Emoji Code Library

- **Pichu**
  - [ ] Added to Project Phoenix on DDP
  - [ ] Added to Aizen on DDP
  - [ ] Added to Public Repo for Images
  - [ ] Emoji Code for Aizen added to Emoji Code Library
  - [ ] Emoji Code for PP added

---

*Continue this format for each additional Pokémon on your list.*

**Comment by Xieon** [comment]
This was opened in November - It's Mid-Feb and no one assisted with what I asked which I went through the trouble of even making a check list. 

I'll get around to doing it like everything else - I'll write a script or something to scrape the images and then move them where they need to be. The serverdex was/is one of XGC's biggest features/money makers/assets - and it should've been completed a lot more by now. 

A lot of that is my fault - but the things like this should've been handled

**Comment by Ashke0521** [comment]
Shit I totally forgot to come back to this I am so sorry. I got busy and then it swiss cheese out of my mind 🤦‍♀️

Once I get back home from work I'll get to this I'll just need to sit down with you again on the steps and make sure to take notes this time so that I can refrence them when my brain blanks. This won't be until Tuesday at the earliest though.
